### ISSUE TITLE
Would it be possible to add support for display 0x0154?

### ISSUE THREAD

**Issue by rtek1000** [stevstrong/Adafruit_TFTLCD_8bit_STM32#13]
Hello,

The display works fine on the Arduino Mega2560, but I'm trying to adapt a project that uses this library Adafruit_TFTLCD_8bit_STM32.

The library on my display is this:
https://github.com/prenticedavid/MCUFRIEND_kbv

The project that uses the Adafruit_TFTLCD_8bit_STM32 library is this:
(An open source firmware for DSO-138 Oscilloscope)
https://github.com/ardyesp/DLO-138

Thank you!

**Comment by stevstrong** [comment]
The right place to discuss about features is: http://www.stm32duino.com/viewforum.php?f=9.

**Comment by rtek1000** [comment]
Thank you for your attention!

Posted:

([stevstrong/Adafruit_TFTLCD_8bit_STM32] Would it be possible to add support for display 0x0154?)
http://www.stm32duino.com/viewtopic.php?f=15&t=3886
