### ISSUE TITLE
libmaple dependency

### ISSUE THREAD

**Issue by philbowles** [stevstrong/Adafruit_TFTLCD_8bit_STM32#16]
Not everyone has libmaple. You need to let people know the dependencies before they waste their time downloading it

**Comment by stevstrong** [comment]
Thanks for pointing out.
Fixed with https://github.com/stevstrong/Adafruit_TFTLCD_8bit_STM32/commit/66ef226fd06d1f5b7522772858f68ab93ffc7739.
