### ISSUE TITLE
port for libopencm3?

### ISSUE THREAD

**Issue by vitasam** [stevstrong/Adafruit_TFTLCD_8bit_STM32#17]
Hello,
what do you think about porting of `Adafruit_TFTLCD_8bit_STM32 `for [libopencm3 ](https://github.com/libopencm3/libopencm3)?

**Comment by stevstrong** [comment]
I do not have any interest in doing that, but I could support you if you do it.

**Comment by vitasam** [comment]
Thanks for proposing help. We are trying now to build this TFT lib for some of my hobby project under libopencm3,  if it will fly I will consider to contribute

**Comment by stevstrong** [comment]
For porting consider to fork this project where then you can make the necessary changes.
