### ISSUE TITLE
Problem bmp file show

### ISSUE THREAD

**Issue by MohammadMokhalled** [stevstrong/Adafruit_TFTLCD_8bit_STM32#4]
I change the tftBMP example's library to this:
`#include <Adafruit_TFTLCD_8bit_STM32.h> // Hardware-specific library`

and define pins and... but when I complie it I have this error:
`                       
                 
                       Arduino: 1.8.3 (Windows 10), Board: "Generic STM32F103C series, STM32F103C8 (20k RAM. 64k Flash),STLink, 72Mhz (Normal)"

                                                C:\Users\Mohammad\Documents\Arduino\LCDBMPTest\LCDBMPTest.ino: In function 'void bmpDraw(char*, int, int)':

                  LCDBMPTest:220: error: 'class Adafruit_TFTLCD_8bit_STM32' has no member named 'color565'

                             lcdbuffer[lcdidx++] = tft.color565(r,g,b);

                                       ^

                     exit status 1
                   'class Adafruit_TFTLCD_8bit_STM32' has no member named 'color565'
`

**Comment by stevstrong** [comment]
Should be solved by this commit: https://github.com/stevstrong/Adafruit_TFTLCD_8bit_STM32/commit/252d8cd24d379906c263b82924ef07f8f5134348.
So I will close this issue.
However, you can comment on it if you think it is not yet solved.
