### ISSUE TITLE
New sub-type of HD8357?

### ISSUE THREAD

**Issue by tfry-git** [stevstrong/Adafruit_TFTLCD_8bit_STM32#6]
So I bought a board like this (https://www.ebay.de/itm/2-4-TFT-LCD-Display-Shield-Touch-Panel-ILI9341-240X320-for-Arduino-UNO-MEGA/192163706724?epid=7008035186&hash=item2cbdd97764:g:PDoAAOSwRUhY-IYe), sold as an ILI9341.

The ID is read out as "3838" (unknown). Turns out I can drive it by using tft.begin (0x8357). However, everything is mirrored, then. I can "fix" the mirroring using the patch, below, but obviously, it would be better if this would be handled by a #define, and best, if it was detected, automatically. Any further info I can provide to help?

```
diff --git a/Adafruit_TFTLCD_8bit_STM32.cpp b/Adafruit_TFTLCD_8bit_STM32.cpp
index 3bcf96e..44d1de9 100644
--- a/Adafruit_TFTLCD_8bit_STM32.cpp
+++ b/Adafruit_TFTLCD_8bit_STM32.cpp
@@ -412,17 +412,17 @@ void Adafruit_TFTLCD_8bit_STM32::setRotation(uint8_t x)
     
     switch (rotation) {
       case 1:
-        t = HX8357B_MADCTL_MY | HX8357B_MADCTL_MV | HX8357B_MADCTL_RGB;
+        t = HX8357B_MADCTL_MV | HX8357B_MADCTL_RGB;
         break;
       case 2:
-        t = HX8357B_MADCTL_RGB;
+        t = HX8357B_MADCTL_MX | HX8357B_MADCTL_RGB;
         break;
       case 3:
-        t = HX8357B_MADCTL_MX | HX8357B_MADCTL_MV | HX8357B_MADCTL_RGB;
+        t = HX8357B_MADCTL_MY | HX8357B_MADCTL_MX | HX8357B_MADCTL_MV | HX8357B_MADCTL_RGB;
         break;
       case 0:
       default:
-        t = HX8357B_MADCTL_MX | HX8357B_MADCTL_MY | HX8357B_MADCTL_RGB;
+        t = HX8357B_MADCTL_MY | HX8357B_MADCTL_RGB;
         break;
     }
     writeRegister8(ILI9341_MADCTL, t ); // MADCTL

```

**Comment by stevstrong** [comment]
For unknown displays it is suggested to first run the [LCD_ID_readreg](https://github.com/prenticedavid/MCUFRIEND_kbv/blob/master/examples/LCD_ID_readreg/LCD_ID_readreg.ino) example.
Please adapt that sketch to your pining, for that please use the PXY (PA3, PC14) notation, and post here the serial output monitor result. This will determine the real type of your display.
Btw, I cannot process the patch you attached in this form. It would be better if you could submit a PR.

**Comment by tfry-git** [comment]
Here's the LCD_ID_readreg output:

```
reg(0x0000) 00 00	ID: ILI9320, ILI9325, ILI9335, ...
reg(0x0004) 00 54 80 66	Manufacturer ID
reg(0x0009) 00 00 61 00 00	Status Register
reg(0x000A) 00 08	Get Power Mode
reg(0x000C) 00 06	Get Pixel Format
reg(0x0061) 00 00	RDID1 HX8347-G
reg(0x0062) 00 00	RDID2 HX8347-G
reg(0x0063) 00 00	RDID3 HX8347-G
reg(0x0064) 00 00	RDID1 HX8347-A
reg(0x0065) 00 00	RDID2 HX8347-A
reg(0x0066) 00 00	RDID3 HX8347-A
reg(0x0067) 00 00	RDID Himax HX8347-A
reg(0x0070) 00 00	Panel Himax HX8347-A
reg(0x00A1) 00 00 00 00 00	RD_DDB SSD1963
reg(0x00B0) 00 00	RGB Interface Signal Control
reg(0x00B4) 00 02	Inversion Control
reg(0x00B6) 00 0A 02 27 27	Display Control
reg(0x00B7) 00 06	Entry Mode Set
reg(0x00BF) 00 00 00 00 00 00	ILI9481, HX8357-B
reg(0x00C0) 00 26 01 01 01 01 01 01 01	Panel Control
reg(0x00C8) 00 00 00 00 00 00 00 00 00 00 00 00 00	GAMMA
reg(0x00CC) 00 31	Panel Control
reg(0x00D0) 00 00 00	Power Control
reg(0x00D2) 00 00 00 00 00	NVM Read
reg(0x00D3) 00 00 93 38	ILI9341, ILI9488
reg(0x00D4) 00 00 00 00	Novatek ID
reg(0x00DA) 00 54	RDID1
reg(0x00DB) 00 80	RDID2
reg(0x00DC) 00 66	RDID3
reg(0x00E0) 00 0F 22 1B 05 0C 03 49 47 3D 03 1C 04 13 0E 00	GAMMA-P
reg(0x00E1) 00 00 23 26 05 10 04 39 24 4B 03 0B 0B 33 37 0F	GAMMA-N
reg(0x00EF) 00 00 00 00 00 00	ILI9327
reg(0x00F2) 00 00 00 00 00 00 00 00 00 00 00 00	Adjust Control 2
reg(0x00F6) 00 00 00 00	Interface Control
```

So from a totally naive look this might suggest an ILI9338? However, as written, of the drivers in your lib, the 8357 is the only one that works (but mirrored). Forcing any other value in tft.begin() gives me a blank white screen (interlaced, for some values).

BTW, I did not mean my "patch" to be applied, as it would very likely break "real" HD8357 displays, only to give an idea of the difference. If there is _not_ a better solution, I'll be happy to submit a PR with an appropriate #define.

**Comment by stevstrong** [comment]
I don´t like `#ifdef`s.
I think a good solution would be:
- insert `#define ID_9338 4` [here](https://github.com/stevstrong/Adafruit_TFTLCD_8bit_STM32/blob/master/Adafruit_TFTLCD_8bit_STM32.h#L22).
- insert [here](https://github.com/stevstrong/Adafruit_TFTLCD_8bit_STM32/blob/master/Adafruit_TFTLCD_8bit_STM32.cpp#L49)
```
} else if (id == 0x9338) {
		// ILI9338
		driver = ID_9338;
		hx8357x_begin();
}
```
- insert [here](https://github.com/stevstrong/Adafruit_TFTLCD_8bit_STM32/blob/master/Adafruit_TFTLCD_8bit_STM32.cpp#L432) your working version `} else if (driver == ID_9338) {...`
- extend each other occurrence of `|| (driver == ID_HX8357D)` by inserting `|| (driver == ID_9338)`
