### ISSUE TITLE
multiple definition errors due to #include <Adafruit_GFX_AS.h>

### ISSUE THREAD

**Issue by tfry-git** [stevstrong/Adafruit_TFTLCD_8bit_STM32#7]
Most examples #include <Adafruit_GFX.h>, while Adafruit_TFTLCD_8bit_STM32.h has #include <Adafruit_GFX_AS.h>. This results in "multiple definition" errors while compiling.

Adafruit_TFTLCD_8bit_STM32.h should either #include <Adafruit_GFX.h>, instead of <Adafruit_GFX_AS.h>, _or_ the examples should omit the #include <Adafruit_GFX.h> line, _or_ both.

**Comment by stevstrong** [comment]
That is true.
Different examples were tested and committed at different time points, so they are not necessarily synchronized with the latest lib status.
The latest tested example is the graphicstest, the rest was not tested with the latest development version.
My intention is to include in the sketches only the lib header, which in turn includes the default Adafruit_GFX_AS lib from the [Arduino_STM32 core](https://github.com/stevstrong/Arduino_STM32).
I will have to change the readme to mirror this.
Meanwhile you are free to submit some PR(s) which "solves" the issue.

**Comment by tfry-git** [comment]
Ok, will submit a PR. Why Adafruit_GFX_AS? Adafruit_GFX _appears_ to work fine, for me. And Adafruit_GFX_AS did not get any updates in three years (in contrast to Adafruit_GFX).

**Comment by stevstrong** [comment]
Fixed by #9 .
